export const RouterConstant = {
  SIGNUP: "signup",
  SIGNIN: "signin",
  SPLASH: "splash",
  HOME: "home",
  CREATE: "create",
  PROFILE: "profile",
  MYTASK: "mytask",
  POLICY: "policy",
  NOTIFICATION: "notification",
  HELP: "help",
  ABOUT: "about",
  TABS: "tabs",
  THEME: "theme",
  LANGUAGE: "language",
  SETTINGS: "settings",
  EDITPROFILE: "editprofile",
  EMPLOYEES: "employees",
  TASKDETAILS: "taskdetails",
  EDITTASK: "edittask"
};
